version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for vcpkg
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Enable version updates for CMake
  - package-ecosystem: "cmake"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "maintainer-team"
    assignees:
      - "maintainer-team"
    commit-message:
      prefix: "build"
      include: "scope"
